// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 03-ClientStreaming/proto/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_c229f24fdb3d1212, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetLongRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetLongRequest) Reset()         { *m = GreetLongRequest{} }
func (m *GreetLongRequest) String() string { return proto.CompactTextString(m) }
func (*GreetLongRequest) ProtoMessage()    {}
func (*GreetLongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c229f24fdb3d1212, []int{1}
}

func (m *GreetLongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetLongRequest.Unmarshal(m, b)
}
func (m *GreetLongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetLongRequest.Marshal(b, m, deterministic)
}
func (m *GreetLongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetLongRequest.Merge(m, src)
}
func (m *GreetLongRequest) XXX_Size() int {
	return xxx_messageInfo_GreetLongRequest.Size(m)
}
func (m *GreetLongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetLongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetLongRequest proto.InternalMessageInfo

func (m *GreetLongRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetLongResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetLongResponse) Reset()         { *m = GreetLongResponse{} }
func (m *GreetLongResponse) String() string { return proto.CompactTextString(m) }
func (*GreetLongResponse) ProtoMessage()    {}
func (*GreetLongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c229f24fdb3d1212, []int{2}
}

func (m *GreetLongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetLongResponse.Unmarshal(m, b)
}
func (m *GreetLongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetLongResponse.Marshal(b, m, deterministic)
}
func (m *GreetLongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetLongResponse.Merge(m, src)
}
func (m *GreetLongResponse) XXX_Size() int {
	return xxx_messageInfo_GreetLongResponse.Size(m)
}
func (m *GreetLongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetLongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetLongResponse proto.InternalMessageInfo

func (m *GreetLongResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetLongRequest)(nil), "greet.GreetLongRequest")
	proto.RegisterType((*GreetLongResponse)(nil), "greet.GreetLongResponse")
}

func init() {
	proto.RegisterFile("03-ClientStreaming/proto/greet.proto", fileDescriptor_c229f24fdb3d1212)
}

var fileDescriptor_c229f24fdb3d1212 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0xad, 0xb0, 0x6b, 0xf3, 0x3c, 0xa8, 0x39, 0xe8, 0xa2, 0x08, 0x12, 0x3c, 0x2c, 0x2c,
	0xee, 0x4a, 0x7b, 0x57, 0x50, 0xd0, 0x8b, 0x78, 0x48, 0x6f, 0x5e, 0x24, 0x95, 0x67, 0x08, 0xb4,
	0x49, 0x4d, 0x52, 0x7f, 0xbf, 0xf4, 0xb5, 0x95, 0xc0, 0xde, 0xde, 0xcc, 0x17, 0x66, 0x86, 0xc0,
	0xed, 0x7d, 0x79, 0xf7, 0xdc, 0x18, 0xb4, 0xb1, 0x8a, 0x1e, 0x55, 0x6b, 0xac, 0xde, 0x75, 0xde,
	0x45, 0xb7, 0xd3, 0x1e, 0x31, 0x6e, 0xe9, 0xe6, 0x0b, 0x12, 0xe2, 0x05, 0xf2, 0xd7, 0xe1, 0x30,
	0x56, 0xf3, 0x6b, 0x80, 0x6f, 0xe3, 0x43, 0xfc, 0xb4, 0xaa, 0xc5, 0x55, 0x76, 0x93, 0xad, 0x99,
	0x64, 0xe4, 0xbc, 0xab, 0x16, 0xf9, 0x15, 0xb0, 0x46, 0xcd, 0xf4, 0x90, 0x68, 0x3e, 0x18, 0x03,
	0x14, 0x8f, 0x70, 0x4a, 0x39, 0x6f, 0xce, 0x6a, 0x89, 0x3f, 0x3d, 0x86, 0xc8, 0x37, 0x90, 0xeb,
	0x29, 0x9b, 0xd2, 0x8e, 0x8b, 0x93, 0xed, 0x38, 0x61, 0xae, 0x94, 0xff, 0x0f, 0xc4, 0x06, 0xce,
	0x92, 0x80, 0xd0, 0x39, 0x1b, 0x90, 0x9f, 0xc3, 0xd2, 0x63, 0xe8, 0x9b, 0x38, 0xad, 0x99, 0x54,
	0x21, 0x93, 0xb6, 0x0a, 0xfd, 0xaf, 0xf9, 0x42, 0xfe, 0x00, 0x0b, 0xf2, 0xf8, 0x45, 0x5a, 0x92,
	0xec, 0xb9, 0x5c, 0xed, 0x83, 0xb1, 0x47, 0x1c, 0xac, 0xb3, 0x27, 0xf6, 0x71, 0x44, 0xb8, 0xab,
	0xeb, 0x25, 0x7d, 0x51, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x5d, 0x88, 0xca, 0x4a, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetLongServiceClient is the client API for GreetLongService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetLongServiceClient interface {
	Greet(ctx context.Context, opts ...grpc.CallOption) (GreetLongService_GreetClient, error)
}

type greetLongServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetLongServiceClient(cc *grpc.ClientConn) GreetLongServiceClient {
	return &greetLongServiceClient{cc}
}

func (c *greetLongServiceClient) Greet(ctx context.Context, opts ...grpc.CallOption) (GreetLongService_GreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetLongService_serviceDesc.Streams[0], "/greet.GreetLongService/Greet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetLongServiceGreetClient{stream}
	return x, nil
}

type GreetLongService_GreetClient interface {
	Send(*GreetLongRequest) error
	CloseAndRecv() (*GreetLongResponse, error)
	grpc.ClientStream
}

type greetLongServiceGreetClient struct {
	grpc.ClientStream
}

func (x *greetLongServiceGreetClient) Send(m *GreetLongRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetLongServiceGreetClient) CloseAndRecv() (*GreetLongResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GreetLongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetLongServiceServer is the server API for GreetLongService service.
type GreetLongServiceServer interface {
	Greet(GreetLongService_GreetServer) error
}

// UnimplementedGreetLongServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetLongServiceServer struct {
}

func (*UnimplementedGreetLongServiceServer) Greet(srv GreetLongService_GreetServer) error {
	return status.Errorf(codes.Unimplemented, "method Greet not implemented")
}

func RegisterGreetLongServiceServer(s *grpc.Server, srv GreetLongServiceServer) {
	s.RegisterService(&_GreetLongService_serviceDesc, srv)
}

func _GreetLongService_Greet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetLongServiceServer).Greet(&greetLongServiceGreetServer{stream})
}

type GreetLongService_GreetServer interface {
	SendAndClose(*GreetLongResponse) error
	Recv() (*GreetLongRequest, error)
	grpc.ServerStream
}

type greetLongServiceGreetServer struct {
	grpc.ServerStream
}

func (x *greetLongServiceGreetServer) SendAndClose(m *GreetLongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetLongServiceGreetServer) Recv() (*GreetLongRequest, error) {
	m := new(GreetLongRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetLongService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetLongService",
	HandlerType: (*GreetLongServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Greet",
			Handler:       _GreetLongService_Greet_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "03-ClientStreaming/proto/greet.proto",
}
